export type LibraryMagazine = {
  id: number
  slug: string
  title: string
  rating: number
  views: string
  downloads: string
  image: string
  genre: string
  rank: number
  shortDescription: string
  fullDescription: string
  readers: string
  subscribers?: string
  parts: number
  trailerUrl?: string
  pdfFile: string
  series?: string
}

// Base URL for remote comics API (from Excel sheet)
export const COMICS_API_BASE = "https://api.ameora.fun"

// Helper function to get ebook thumbnails (cycling through 85 images)
function getEbookThumbnail(index: number) {
  const i = ((index - 1) % 85) + 1 // Cycle through 1-85
  return `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/${i}.png`
}

// Helper function to get Batman comic URLs
function getBatmanComic(index: number) {
  const i = ((index - 1) % 50) + 1 // Cycle through 1-50
  // Batman images are from ebook212pxx256px/1.png to 50.png (50 images)
  const imageIndex = i // 1-50
  return {
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/${imageIndex}.png`,
    pdfFile: `${COMICS_API_BASE}/content/comics/batman/bmp${i}/bms${i}.pdf`,
  }
}

// Helper function to get Donald Duck comic URLs
function getDonaldDuckComic(index: number) {
  const i = ((index - 1) % 10) + 1 // Cycle through 1-10
  // Donald Duck images are from ebook212pxx256px/52.png to 61.png (10 images)
  const imageIndex = 51 + i // 52-61
  return {
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/${imageIndex}.png`,
    pdfFile: `${COMICS_API_BASE}/content/comics/donald_duck/ddp${i}/dds${i}.pdf`,
  }
}

// Helper function to get Mickey Mouse comic URLs
function getMickeyMouseComic(index: number) {
  const i = ((index - 1) % 18) + 1 // Cycle through 1-18
  // Mickey Mouse images are from ebook212pxx256px/68.png to 85.png (18 images)
  const imageIndex = 67 + i // 68-85
  return {
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/${imageIndex}.png`,
    pdfFile: `${COMICS_API_BASE}/content/comics/mickey_mouse/mmp${i}/mms${i}.pdf`,
  }
}

// Generate Batman comics from Excel data (50 comics)
export const batmanComics: LibraryMagazine[] = Array.from({ length: 50 }, (_, i) => {
  const comic = getBatmanComic(i + 1)
  return {
    id: 1000 + i + 1,
    slug: `batman-${i + 1}`,
    title: `باتمان - الحلقة ${i + 1}`,
    rating: Number((4.5 + (i % 5) * 0.1).toFixed(1)),
    views: `${300 + i * 10}K`,
    downloads: `${100 + i * 5}K`,
    image: comic.image,
    genre: "باتمان",
    rank: i + 1,
    shortDescription: `مغامرات الفارس المظلم - الحلقة ${i + 1}`,
    fullDescription: `استمتع بمغامرات باتمان المثيرة في مدينة جوثام. الفارس المظلم يواجه أعداءه في معارك ملحمية. حلقة ${i + 1} مليئة بالإثارة والتشويق.`,
    readers: `${300 + i * 10}K`,
    subscribers: `${200 + i * 5}K`,
    parts: 10 + (i % 10),
    pdfFile: comic.pdfFile,
    series: "batman",
  }
})

// Generate Donald Duck comics from Excel data (10 comics)
export const donaldDuckComics: LibraryMagazine[] = Array.from({ length: 10 }, (_, i) => {
  const comic = getDonaldDuckComic(i + 1)
  return {
    id: 2000 + i + 1,
    slug: `donald-duck-${i + 1}`,
    title: `بطوط - الحلقة ${i + 1}`,
    rating: Number((4.3 + (i % 5) * 0.1).toFixed(1)),
    views: `${200 + i * 20}K`,
    downloads: `${80 + i * 10}K`,
    image: comic.image,
    genre: "بطوط",
    rank: i + 1,
    shortDescription: `مغامرات بطوط الكوميدية - الحلقة ${i + 1}`,
    fullDescription: `انضم إلى بطوط في مغامراته الكوميدية المضحكة مع أبناء أخيه حظوظ وفظوظ ولظوظ. حلقة ${i + 1} مليئة بالمرح.`,
    readers: `${200 + i * 20}K`,
    subscribers: `${150 + i * 10}K`,
    parts: 6 + (i % 6),
    pdfFile: comic.pdfFile,
    series: "donald_duck",
  }
})

// Generate Mickey Mouse comics from Excel data (18 comics)
export const mickeyMouseComics: LibraryMagazine[] = Array.from({ length: 18 }, (_, i) => {
  const comic = getMickeyMouseComic(i + 1)
  return {
    id: 3000 + i + 1,
    slug: `mickey-mouse-${i + 1}`,
    title: `ميكي ماوس - الحلقة ${i + 1}`,
    rating: Number((4.4 + (i % 5) * 0.1).toFixed(1)),
    views: `${250 + i * 15}K`,
    downloads: `${90 + i * 8}K`,
    image: comic.image,
    genre: "ميكي ماوس",
    rank: i + 1,
    shortDescription: `مغامرات ميكي ماوس - الحلقة ${i + 1}`,
    fullDescription: `انطلق مع ميكي ماوس في مغامرة جديدة مليئة بالمرح والإثارة مع أصدقائه. حلقة ${i + 1} ممتعة للجميع.`,
    readers: `${250 + i * 15}K`,
    subscribers: `${180 + i * 8}K`,
    parts: 7 + (i % 7),
    pdfFile: comic.pdfFile,
    series: "mickey_mouse",
  }
})

// Main library magazines - ALL mapped to Excel API URLs
export const libraryMagazines: LibraryMagazine[] = [
  // Superhero/خارقة genre - mapped to Batman comics
  {
    id: 1,
    slug: "ملحمة-اللانهاية",
    title: "ملحمة اللانهاية",
    rating: 4.9,
    views: "2.4M",
    downloads: "856K",
    ...getBatmanComic(1),
    genre: "خارقة",
    rank: 1,
    shortDescription: "المعركة النهائية عبر الحقائق اللانهائية",
    fullDescription: "في هذه الملحمة الكبرى، يواجه أبطال الأكوان المتعددة تهديدًا كونيًا يمحو العوالم واحدًا تلو الآخر.",
    readers: "2.4M",
    subscribers: "2.4M",
    parts: 18,
    series: "batman",
  },
  {
    id: 2,
    slug: "الأساطير-الكونية",
    title: "الأساطير الكونية",
    rating: 4.8,
    views: "1.9M",
    downloads: "623K",
    ...getBatmanComic(2),
    genre: "خيال علمي",
    rank: 2,
    shortDescription: "مغامرات فضائية ملحمية تتجاوز الخيال",
    fullDescription: "رحلة بين النجوم تتابع طاقم سفينة استكشافية يكتشفون حضارات مفقودة وقوى قديمة.",
    readers: "1.9M",
    subscribers: "1.8M",
    parts: 12,
    series: "batman",
  },
  {
    id: 3,
    slug: "سجلات-عالم-الظل",
    title: "سجلات عالم الظل",
    rating: 4.8,
    views: "1.7M",
    downloads: "589K",
    ...getBatmanComic(3),
    genre: "خيالي",
    rank: 3,
    shortDescription: "تتكشف السحر الأسود والأسرار القديمة",
    fullDescription: "بين ممالك الضوء والظلام، يقف حارس أخير يحاول منع اندلاع حرب سحرية.",
    readers: "1.7M",
    subscribers: "1.5M",
    parts: 20,
    series: "batman",
  },
  {
    id: 4,
    slug: "محاربي-النيون",
    title: "محاربي النيون",
    rating: 4.7,
    views: "1.5M",
    downloads: "445K",
    ...getBatmanComic(4),
    genre: "السايبربانك",
    rank: 4,
    shortDescription: "معارك التكنولوجيا الفائقة في مستقبل بائس",
    fullDescription: "في مدينة تغمرها الأضواء النيونية والشبكات العصبية، يقاتل محاربو الظل.",
    readers: "1.5M",
    subscribers: "1.3M",
    parts: 10,
    series: "batman",
  },
  {
    id: 5,
    slug: "حراس-الوقت",
    title: "حراس الوقت",
    rating: 4.7,
    views: "1.3M",
    downloads: "412K",
    ...getBatmanComic(5),
    genre: "خارقة",
    rank: 5,
    shortDescription: "السفر عبر الزمن والمعارك الكونية",
    fullDescription: "فريق من الأبطال يسافر عبر الزمن لمنع كوارث كونية تهدد الوجود نفسه.",
    readers: "1.3M",
    subscribers: "1.1M",
    parts: 15,
    series: "batman",
  },
  {
    id: 6,
    slug: "أساطير-المجرة",
    title: "أساطير المجرة",
    rating: 4.6,
    views: "1.2M",
    downloads: "378K",
    ...getBatmanComic(6),
    genre: "خيال علمي",
    rank: 6,
    shortDescription: "مغامرات فضائية بين النجوم",
    fullDescription: "استكشاف أعماق الفضاء والمواجهة مع حضارات غريبة في رحلة ملحمية.",
    readers: "1.2M",
    subscribers: "1.0M",
    parts: 14,
    series: "batman",
  },
  {
    id: 7,
    slug: "الفارس-الأسود",
    title: "الفارس الأسود",
    rating: 4.6,
    views: "1.1M",
    downloads: "345K",
    ...getBatmanComic(7),
    genre: "خارقة",
    rank: 7,
    shortDescription: "حارس الظلام يحمي المدينة",
    fullDescription: "بطل مقنع يخوض معاركه في الظلام ضد قوى الشر التي تهدد المدينة.",
    readers: "1.1M",
    subscribers: "950K",
    parts: 16,
    series: "batman",
  },
  {
    id: 8,
    slug: "عاصفة-الرعد",
    title: "عاصفة الرعد",
    rating: 4.5,
    views: "980K",
    downloads: "312K",
    ...getBatmanComic(8),
    genre: "خارقة",
    rank: 8,
    shortDescription: "قوة البرق تحمي الأبرياء",
    fullDescription: "بطل يمتلك قوة الصواعق يستخدم قدراته لحماية العالم من التهديدات.",
    readers: "980K",
    subscribers: "850K",
    parts: 12,
    series: "batman",
  },
  {
    id: 9,
    slug: "حارس-الليل",
    title: "حارس الليل",
    rating: 4.5,
    views: "920K",
    downloads: "298K",
    ...getBatmanComic(9),
    genre: "خارقة",
    rank: 9,
    shortDescription: "المنتقم في الظلام",
    fullDescription: "محارب يعمل في الظل لمحاربة الجريمة وحماية الضعفاء.",
    readers: "920K",
    subscribers: "800K",
    parts: 11,
    series: "batman",
  },
  {
    id: 10,
    slug: "الصقر-الذهبي",
    title: "الصقر الذهبي",
    rating: 4.4,
    views: "870K",
    downloads: "276K",
    ...getBatmanComic(10),
    genre: "خارقة",
    rank: 10,
    shortDescription: "بطل يحلق في السماء",
    fullDescription: "محارب مجنح يدافع عن العدالة من السماء بقوى خارقة.",
    readers: "870K",
    subscribers: "750K",
    parts: 13,
    series: "batman",
  },
  // Mickey Mouse genre magazines
  {
    id: 11,
    slug: "مغامرات-ميكي",
    title: "مغامرات ميكي",
    rating: 4.8,
    views: "1.5M",
    downloads: "520K",
    ...getMickeyMouseComic(1),
    genre: "ميكي ماوس",
    rank: 11,
    shortDescription: "مغامرات ميكي ماوس الممتعة",
    fullDescription: "انضم إلى ميكي ماوس في مغامراته الشيقة مع أصدقائه في عالم مليء بالمرح.",
    readers: "1.5M",
    subscribers: "1.2M",
    parts: 15,
    series: "mickey_mouse",
  },
  {
    id: 12,
    slug: "ميكي-والأصدقاء",
    title: "ميكي والأصدقاء",
    rating: 4.7,
    views: "1.3M",
    downloads: "450K",
    ...getMickeyMouseComic(2),
    genre: "ميكي ماوس",
    rank: 12,
    shortDescription: "ميكي وأصدقاؤه في مغامرات جديدة",
    fullDescription: "ميكي وميني وجوفي وبلوتو في مغامرات مثيرة ومضحكة.",
    readers: "1.3M",
    subscribers: "1.1M",
    parts: 12,
    series: "mickey_mouse",
  },
  {
    id: 13,
    slug: "عالم-ميكي-السحري",
    title: "عالم ميكي السحري",
    rating: 4.6,
    views: "1.1M",
    downloads: "380K",
    ...getMickeyMouseComic(3),
    genre: "ميكي ماوس",
    rank: 13,
    shortDescription: "ميكي في عالم السحر",
    fullDescription: "ميكي يكتشف عالمًا سحريًا مليئًا بالمفاجآت والمغامرات.",
    readers: "1.1M",
    subscribers: "950K",
    parts: 10,
    series: "mickey_mouse",
  },
  // Donald Duck genre magazines
  {
    id: 14,
    slug: "مغامرات-بطوط",
    title: "مغامرات بطوط",
    rating: 4.7,
    views: "1.4M",
    downloads: "480K",
    ...getDonaldDuckComic(1),
    genre: "بطوط",
    rank: 14,
    shortDescription: "مغامرات بطوط الكوميدية",
    fullDescription: "بطوط في مغامرات مضحكة مع عائلته وأصدقائه في قصص مليئة بالمرح.",
    readers: "1.4M",
    subscribers: "1.2M",
    parts: 14,
    series: "donald_duck",
  },
  {
    id: 15,
    slug: "بطوط-والكنز",
    title: "بطوط والكنز",
    rating: 4.6,
    views: "1.2M",
    downloads: "410K",
    ...getDonaldDuckComic(2),
    genre: "بطوط",
    rank: 15,
    shortDescription: "بطوط يبحث عن الكنز",
    fullDescription: "بطوط وأبناء أخيه في رحلة بحث عن كنز قديم مخبأ.",
    readers: "1.2M",
    subscribers: "1.0M",
    parts: 11,
    series: "donald_duck",
  },
  {
    id: 16,
    slug: "عم-دهب-والثروة",
    title: "عم دهب والثروة",
    rating: 4.5,
    views: "1.0M",
    downloads: "350K",
    ...getDonaldDuckComic(3),
    genre: "بطوط",
    rank: 16,
    shortDescription: "مغامرات عم دهب",
    fullDescription: "عم دهب في مغامرات للحفاظ على ثروته من اللصوص.",
    readers: "1.0M",
    subscribers: "850K",
    parts: 9,
    series: "donald_duck",
  },
  // Action/فعل genre - mapped to Batman
  {
    id: 17,
    slug: "المحاربين-العنصريين",
    title: "المحاربين العنصريين",
    rating: 4.4,
    views: "460K",
    downloads: "180K",
    ...getBatmanComic(11),
    genre: "فعل",
    rank: 17,
    shortDescription: "أسياد النار والماء والأرض والهواء يتحدون",
    fullDescription: "محاربون يتحكمون بالعناصر الأربعة يتحدون لمواجهة تهديد كوني.",
    readers: "460K",
    subscribers: "380K",
    parts: 12,
    series: "batman",
  },
  {
    id: 18,
    slug: "المحارب-الوحيد",
    title: "المحارب الوحيد",
    rating: 4.7,
    views: "680K",
    downloads: "250K",
    ...getBatmanComic(12),
    genre: "فعل",
    rank: 18,
    shortDescription: "محارب وحيد ضد الجيش",
    fullDescription: "محارب وحيد يواجه جيشًا كاملًا لحماية قريته من الدمار.",
    readers: "680K",
    subscribers: "550K",
    parts: 15,
    series: "batman",
  },
  {
    id: 19,
    slug: "معركة-الأبطال",
    title: "معركة الأبطال",
    rating: 4.6,
    views: "620K",
    downloads: "230K",
    ...getBatmanComic(13),
    genre: "فعل",
    rank: 19,
    shortDescription: "معركة ملحمية بين الأبطال",
    fullDescription: "أبطال من عوالم مختلفة يلتقون في معركة ملحمية.",
    readers: "620K",
    subscribers: "500K",
    parts: 14,
    series: "batman",
  },
  // Romance/الرومانسية genre - mapped to Mickey Mouse
  {
    id: 20,
    slug: "حب-في-زمن-الحرب",
    title: "حب في زمن الحرب",
    rating: 4.6,
    views: "420K",
    downloads: "180K",
    ...getMickeyMouseComic(4),
    genre: "الرومانسية",
    rank: 20,
    shortDescription: "قصة حب ملحمية في خضم الحرب",
    fullDescription: "قصة حب مؤثرة تتحدى كل الصعاب في أوقات الحرب.",
    readers: "420K",
    subscribers: "300K",
    parts: 12,
    series: "mickey_mouse",
  },
  {
    id: 21,
    slug: "قلوب-متحدة",
    title: "قلوب متحدة",
    rating: 4.5,
    views: "380K",
    downloads: "160K",
    ...getMickeyMouseComic(5),
    genre: "الرومانسية",
    rank: 21,
    shortDescription: "قصة حب تتحدى كل الصعاب",
    fullDescription: "قصة حب رومانسية بين شخصين من خلفيات مختلفة.",
    readers: "380K",
    subscribers: "280K",
    parts: 10,
    series: "mickey_mouse",
  },
  {
    id: 22,
    slug: "عاشق-الليل",
    title: "عاشق الليل",
    rating: 4.4,
    views: "350K",
    downloads: "150K",
    ...getMickeyMouseComic(6),
    genre: "الرومانسية",
    rank: 22,
    shortDescription: "قصة حب غامضة في المدينة",
    fullDescription: "قصة حب مثيرة بين محقق ومشتبه بها في قضية غامضة.",
    readers: "350K",
    subscribers: "250K",
    parts: 8,
    series: "mickey_mouse",
  },
  // Horror/رعب genre - mapped to Batman
  {
    id: 23,
    slug: "ليالي-الرعب",
    title: "ليالي الرعب",
    rating: 4.5,
    views: "520K",
    downloads: "200K",
    ...getBatmanComic(14),
    genre: "رعب",
    rank: 23,
    shortDescription: "حكايات مرعبة في الظلام",
    fullDescription: "مجموعة من القصص المرعبة التي ستجعلك تخاف من الظلام.",
    readers: "520K",
    subscribers: "420K",
    parts: 10,
    series: "batman",
  },
  {
    id: 24,
    slug: "لعنة-القصر",
    title: "لعنة القصر",
    rating: 4.4,
    views: "480K",
    downloads: "185K",
    ...getBatmanComic(15),
    genre: "رعب",
    rank: 24,
    shortDescription: "أسرار مظلمة في قصر مسكون",
    fullDescription: "عائلة تنتقل إلى قصر قديم لتكتشف لعنة قديمة.",
    readers: "480K",
    subscribers: "380K",
    parts: 11,
    series: "batman",
  },
  {
    id: 25,
    slug: "الشبح-الأسود",
    title: "الشبح الأسود",
    rating: 4.3,
    views: "440K",
    downloads: "170K",
    ...getBatmanComic(16),
    genre: "رعب",
    rank: 25,
    shortDescription: "شبح ينتقم من الأحياء",
    fullDescription: "شبح يطارد من ظلمه في حياته السابقة.",
    readers: "440K",
    subscribers: "350K",
    parts: 9,
    series: "batman",
  },
  // Fantasy/خيالي genre - mapped to Donald Duck
  {
    id: 26,
    slug: "أكاديمية-ميستيك",
    title: "أكاديمية ميستيك",
    rating: 4.7,
    views: "890K",
    downloads: "320K",
    ...getDonaldDuckComic(4),
    genre: "خيالي",
    rank: 26,
    shortDescription: "مدرسة للسحر والمغامرات",
    fullDescription: "طالب يكتشف قدراته السحرية في أكاديمية للسحرة.",
    readers: "890K",
    subscribers: "720K",
    parts: 16,
    series: "donald_duck",
  },
  {
    id: 27,
    slug: "ممالك-الخيال",
    title: "ممالك الخيال",
    rating: 4.6,
    views: "820K",
    downloads: "290K",
    ...getDonaldDuckComic(5),
    genre: "خيالي",
    rank: 27,
    shortDescription: "عوالم سحرية لا حدود لها",
    fullDescription: "رحلة عبر ممالك سحرية مليئة بالمخلوقات الأسطورية.",
    readers: "820K",
    subscribers: "660K",
    parts: 14,
    series: "donald_duck",
  },
  {
    id: 28,
    slug: "التنين-الأخير",
    title: "التنين الأخير",
    rating: 4.5,
    views: "760K",
    downloads: "265K",
    ...getDonaldDuckComic(6),
    genre: "خيالي",
    rank: 28,
    shortDescription: "آخر تنين وفارسه",
    fullDescription: "صبي يكتشف آخر تنين في العالم ويصبح فارسه.",
    readers: "760K",
    subscribers: "610K",
    parts: 13,
    series: "donald_duck",
  },
  // Sci-Fi/خيال علمي genre - mapped to Batman
  {
    id: 29,
    slug: "حروب-الفضاء",
    title: "حروب الفضاء",
    rating: 4.6,
    views: "780K",
    downloads: "280K",
    ...getBatmanComic(17),
    genre: "خيال علمي",
    rank: 29,
    shortDescription: "معارك بين الكواكب",
    fullDescription: "حرب كونية بين إمبراطوريات فضائية متناحرة.",
    readers: "780K",
    subscribers: "630K",
    parts: 15,
    series: "batman",
  },
  {
    id: 30,
    slug: "الروبوت-المتمرد",
    title: "الروبوت المتمرد",
    rating: 4.5,
    views: "720K",
    downloads: "255K",
    ...getBatmanComic(18),
    genre: "خيال علمي",
    rank: 30,
    shortDescription: "آلة تبحث عن إنسانيتها",
    fullDescription: "روبوت يكتسب الوعي ويبدأ رحلة البحث عن معنى الحياة.",
    readers: "720K",
    subscribers: "580K",
    parts: 12,
    series: "batman",
  },
  {
    id: 31,
    slug: "المستقبل-البعيد",
    title: "المستقبل البعيد",
    rating: 4.4,
    views: "680K",
    downloads: "235K",
    ...getBatmanComic(19),
    genre: "خيال علمي",
    rank: 31,
    shortDescription: "رؤية للمستقبل البعيد",
    fullDescription: "كيف سيبدو العالم بعد ألف سنة من الآن.",
    readers: "680K",
    subscribers: "540K",
    parts: 11,
    series: "batman",
  },
  // Historical/تاريخية genre - mapped to Mickey Mouse
  {
    id: 32,
    slug: "فارس-القرون",
    title: "فارس القرون",
    rating: 4.5,
    views: "560K",
    downloads: "210K",
    ...getMickeyMouseComic(7),
    genre: "تاريخية",
    rank: 32,
    shortDescription: "بطل من العصور الوسطى",
    fullDescription: "فارس نبيل يدافع عن المملكة ضد الغزاة.",
    readers: "560K",
    subscribers: "450K",
    parts: 13,
    series: "mickey_mouse",
  },
  {
    id: 33,
    slug: "أساطير-الفراعنة",
    title: "أساطير الفراعنة",
    rating: 4.4,
    views: "520K",
    downloads: "195K",
    ...getMickeyMouseComic(8),
    genre: "تاريخية",
    rank: 33,
    shortDescription: "أسرار مصر القديمة",
    fullDescription: "اكتشاف أسرار الفراعنة ولعناتهم القديمة.",
    readers: "520K",
    subscribers: "420K",
    parts: 11,
    series: "mickey_mouse",
  },
  {
    id: 34,
    slug: "محاربي-الساموراي",
    title: "محاربي الساموراي",
    rating: 4.3,
    views: "480K",
    downloads: "180K",
    ...getMickeyMouseComic(9),
    genre: "تاريخية",
    rank: 34,
    shortDescription: "شرف المحاربين اليابانيين",
    fullDescription: "قصة ساموراي يسعى لاستعادة شرفه المفقود.",
    readers: "480K",
    subscribers: "380K",
    parts: 10,
    series: "mickey_mouse",
  },
  // Cyberpunk/السايبربانك genre - mapped to Batman
  {
    id: 35,
    slug: "مدينة-النيون",
    title: "مدينة النيون",
    rating: 4.6,
    views: "640K",
    downloads: "240K",
    ...getBatmanComic(20),
    genre: "السايبربانك",
    rank: 35,
    shortDescription: "مستقبل مظلم ومشرق",
    fullDescription: "في مدينة تغمرها أضواء النيون، يكافح أبطال من أجل الحرية.",
    readers: "640K",
    subscribers: "520K",
    parts: 14,
    series: "batman",
  },
  {
    id: 36,
    slug: "قراصنة-الشبكة",
    title: "قراصنة الشبكة",
    rating: 4.5,
    views: "600K",
    downloads: "220K",
    ...getBatmanComic(21),
    genre: "السايبربانك",
    rank: 36,
    shortDescription: "هاكرز ضد النظام",
    fullDescription: "مجموعة من القراصنة الإلكترونيين يحاربون شركات فاسدة.",
    readers: "600K",
    subscribers: "480K",
    parts: 12,
    series: "batman",
  },
  // More superhero magazines
  {
    id: 37,
    slug: "فريق-العدالة",
    title: "فريق العدالة",
    rating: 4.7,
    views: "1.0M",
    downloads: "380K",
    ...getBatmanComic(22),
    genre: "خارقة",
    rank: 37,
    shortDescription: "أبطال متحدون لإنقاذ العالم",
    fullDescription: "فريق من أقوى الأبطال يتحدون لمواجهة التهديدات الكونية.",
    readers: "1.0M",
    subscribers: "850K",
    parts: 18,
    series: "batman",
  },
  {
    id: 38,
    slug: "الرجل-الحديدي",
    title: "الرجل الحديدي",
    rating: 4.6,
    views: "920K",
    downloads: "340K",
    ...getBatmanComic(23),
    genre: "خارقة",
    rank: 38,
    shortDescription: "عبقري في درع حديدي",
    fullDescription: "مخترع عبقري يصنع درعًا تكنولوجيًا لمحاربة الشر.",
    readers: "920K",
    subscribers: "780K",
    parts: 16,
    series: "batman",
  },
  {
    id: 39,
    slug: "العنكبوت-الخارق",
    title: "العنكبوت الخارق",
    rating: 4.8,
    views: "1.2M",
    downloads: "450K",
    ...getBatmanComic(24),
    genre: "خارقة",
    rank: 39,
    shortDescription: "بطل الحي الودود",
    fullDescription: "شاب يكتسب قوى العنكبوت ويصبح بطلاً خارقًا.",
    readers: "1.2M",
    subscribers: "1.0M",
    parts: 20,
    series: "batman",
  },
  {
    id: 40,
    slug: "المرأة-الخارقة",
    title: "المرأة الخارقة",
    rating: 4.7,
    views: "1.1M",
    downloads: "410K",
    ...getBatmanComic(25),
    genre: "خارقة",
    rank: 40,
    shortDescription: "أميرة محاربة",
    fullDescription: "أميرة من جزيرة خفية تصبح بطلة خارقة.",
    readers: "1.1M",
    subscribers: "920K",
    parts: 17,
    series: "batman",
  },
  // More action magazines
  {
    id: 41,
    slug: "النينجا-الأخير",
    title: "النينجا الأخير",
    rating: 4.5,
    views: "580K",
    downloads: "215K",
    ...getBatmanComic(26),
    genre: "فعل",
    rank: 41,
    shortDescription: "آخر محارب من عشيرته",
    fullDescription: "نينجا وحيد يسعى للانتقام من قتلة عشيرته.",
    readers: "580K",
    subscribers: "470K",
    parts: 13,
    series: "batman",
  },
  {
    id: 42,
    slug: "قبضة-الحديد",
    title: "قبضة الحديد",
    rating: 4.4,
    views: "540K",
    downloads: "200K",
    ...getBatmanComic(27),
    genre: "فعل",
    rank: 42,
    shortDescription: "فنون قتالية خارقة",
    fullDescription: "محارب يتقن فنونًا قتالية قديمة ويستخدمها للعدالة.",
    readers: "540K",
    subscribers: "430K",
    parts: 11,
    series: "batman",
  },
  // More Mickey Mouse
  {
    id: 43,
    slug: "ميكي-المحقق",
    title: "ميكي المحقق",
    rating: 4.6,
    views: "950K",
    downloads: "350K",
    ...getMickeyMouseComic(10),
    genre: "ميكي ماوس",
    rank: 43,
    shortDescription: "ميكي يحل الألغاز",
    fullDescription: "ميكي ماوس يتحول إلى محقق ويحل ألغاز صعبة.",
    readers: "950K",
    subscribers: "800K",
    parts: 14,
    series: "mickey_mouse",
  },
  {
    id: 44,
    slug: "ميكي-في-الفضاء",
    title: "ميكي في الفضاء",
    rating: 4.5,
    views: "880K",
    downloads: "320K",
    ...getMickeyMouseComic(11),
    genre: "ميكي ماوس",
    rank: 44,
    shortDescription: "مغامرات ميكي الفضائية",
    fullDescription: "ميكي يسافر إلى الفضاء في مغامرة مثيرة.",
    readers: "880K",
    subscribers: "740K",
    parts: 12,
    series: "mickey_mouse",
  },
  // More Donald Duck
  {
    id: 45,
    slug: "بطوط-السباق",
    title: "بطوط السباق",
    rating: 4.5,
    views: "820K",
    downloads: "300K",
    ...getDonaldDuckComic(7),
    genre: "بطوط",
    rank: 45,
    shortDescription: "بطوط في سباقات مثيرة",
    fullDescription: "بطوط يدخل سباقات سيارات مليئة بالمفاجآت.",
    readers: "820K",
    subscribers: "680K",
    parts: 10,
    series: "donald_duck",
  },
  {
    id: 46,
    slug: "بطوط-الساحر",
    title: "بطوط الساحر",
    rating: 4.4,
    views: "760K",
    downloads: "275K",
    ...getDonaldDuckComic(8),
    genre: "بطوط",
    rank: 46,
    shortDescription: "بطوط يتعلم السحر",
    fullDescription: "بطوط يحصل على عصا سحرية ويتسبب في فوضى.",
    readers: "760K",
    subscribers: "620K",
    parts: 9,
    series: "donald_duck",
  },
  // Additional magazines for variety - mapped to remaining Batman comics
  {
    id: 47,
    slug: "أبطال-الظل",
    title: "أبطال الظل",
    rating: 4.6,
    views: "720K",
    downloads: "260K",
    ...getBatmanComic(28),
    genre: "خارقة",
    rank: 47,
    shortDescription: "أبطال يعملون في الخفاء",
    fullDescription: "فريق سري من الأبطال يحمي العالم من التهديدات الخفية.",
    readers: "720K",
    subscribers: "590K",
    parts: 14,
    series: "batman",
  },
  {
    id: 48,
    slug: "الساحر-الأعظم",
    title: "الساحر الأعظم",
    rating: 4.5,
    views: "680K",
    downloads: "245K",
    ...getBatmanComic(29),
    genre: "خيالي",
    rank: 48,
    shortDescription: "أقوى ساحر في العالم",
    fullDescription: "ساحر عظيم يحمي العالم من التهديدات السحرية.",
    readers: "680K",
    subscribers: "550K",
    parts: 15,
    series: "batman",
  },
  {
    id: 49,
    slug: "محاربو-الكواكب",
    title: "محاربو الكواكب",
    rating: 4.4,
    views: "640K",
    downloads: "230K",
    ...getBatmanComic(30),
    genre: "خيال علمي",
    rank: 49,
    shortDescription: "دفاع عن المجرة",
    fullDescription: "فريق من المحاربين يدافعون عن الكواكب من الغزو.",
    readers: "640K",
    subscribers: "510K",
    parts: 13,
    series: "batman",
  },
  {
    id: 50,
    slug: "أسطورة-الفينيق",
    title: "أسطورة الفينيق",
    rating: 4.7,
    views: "880K",
    downloads: "320K",
    ...getBatmanComic(31),
    genre: "خيالي",
    rank: 50,
    shortDescription: "طائر النار الأسطوري",
    fullDescription: "محارب يحمل روح الفينيق ويقاتل قوى الظلام.",
    readers: "880K",
    subscribers: "720K",
    parts: 16,
    series: "batman",
  },
]

// Combine all comics including Excel-based comics
export const allLibraryMagazines: LibraryMagazine[] = [
  ...libraryMagazines,
  ...batmanComics,
  ...donaldDuckComics,
  ...mickeyMouseComics,
]

export function getLibraryMagazineBySlug(slug: string) {
  const decoded = decodeURIComponent(slug)

  // Try multiple matching strategies to be robust against encoding / slug differences
  return (
    allLibraryMagazines.find((m) => m.slug === slug) ||
    allLibraryMagazines.find((m) => m.slug === decoded) ||
    allLibraryMagazines.find((m) => encodeURIComponent(m.slug) === slug) ||
    allLibraryMagazines.find((m) => m.title === decoded || m.title === slug)
  )
}

// Get comics by series
export function getComicsBySeries(series: string): LibraryMagazine[] {
  return allLibraryMagazines.filter((m) => m.series === series)
}

// Get comics by genre
export function getComicsByGenre(genre: string): LibraryMagazine[] {
  return allLibraryMagazines.filter((m) => m.genre === genre)
}

// Comic series metadata for category pages
export const comicSeriesCategories = [
  {
    id: "batman",
    slug: "batman",
    name: "باتمان",
    nameEn: "Batman",
    count: batmanComics.length,
    color: "#1A1A2E",
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/1.png`,
    description: "مغامرات الفارس المظلم في مدينة جوثام",
  },
  {
    id: "donald_duck",
    slug: "donald-duck",
    name: "بطوط",
    nameEn: "Donald Duck",
    count: donaldDuckComics.length,
    color: "#0066CC",
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/52.png`,
    description: "مغامرات بطوط الكوميدية المضحكة",
  },
  {
    id: "mickey_mouse",
    slug: "mickey-mouse",
    name: "ميكي ماوس",
    nameEn: "Mickey Mouse",
    count: mickeyMouseComics.length,
    color: "#E31937",
    image: `${COMICS_API_BASE}/content/ecomics/ebook212pxx256px/68.png`,
    description: "مغامرات ميكي ماوس الممتعة",
  },
]
